django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^gradebook/', include('gradebook.urls', namespace="grades")),
    url(r'^admin/', include(admin.site.urls)),
]

gradebook/urls.py
from django.conf.urls import url
from gradebook import views

urlpatterns = [
    # eg: grades/
    url(r'^$', views.index, name='index'),

    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),

    url(r'^courses/$', views.courses, name='courses'),
    url(r'^courses/add/', views.add_course, name='add_course'),
    url(r'^courses/(?P<course_id>\d+)/$', views.course_details, name='course_details'),
    url(r'^courses/(?P<course_id>\d+)/grades/$', views.assign_grades, name='assign_grades'),
    url(r'^courses/(?P<course_id>\d+)/edit/$', views.edit_course, name='edit_course'),
    url(r'^courses/(?P<course_id>\d+)/delete/$', views.delete_course, name='delete_course'),

    url(r'^students/$', views.students, name='students'),
    url(r'^students/add/', views.add_students, name='add_students'),
    url(r'^students/(?P<student_id>\d+)/$', views.student_details, name='student_details'),
    url(r'^students/(?P<student_id>\d+)/edit/$', views.edit_student, name='edit_student'),

    url(r'^assignments/$', views.assignments, name='assignments'),
    url(r'^assignments/add/$', views.add_assignment, name='add_assignment'),
    url(r'^assignments/add_marks/$', views.add_marks, name='add_marks'),
    url(r'^assignments/add_marks/(?P<assignment_id>\d+)/$', views.add_marks, name='add_marks'),
    url(r'^assignments/(?P<assignment_id>\d+)/$', views.assignment_details, name='assignment_details'),
    url(r'^assignments/(?P<assignment_id>\d+)/edit/$', views.edit_assignment, name='edit_assignment'),
    url(r'^assignments/(?P<assignment_id>\d+)/delete/$', views.delete_assignment, name='delete_assignment'),

    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

    url(r'^tutorial/', views.tutorial, name='tutorial'),
]

gradebook/views.py
from collections import Counter, OrderedDict
from datetime import datetime
from django.contrib import auth
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from operator import attrgetter

from gradebook.models import Course, Assignment, Student, Marks


# def validation(username, ...):


def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('grades:courses'))
    else:
        return render(request, 'gradebook/index.html', )


def register(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name', '')
        last_name = request.POST.get('last_name', '')
        email = request.POST.get('email', '')
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        level = request.POST.get('level', '')
        # Remember, validation required!
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        if level == 'professor':
            user.groups.add(Group.objects.get(name='Professors'))
        elif level == 'student':
            user.groups.add(Group.objects.get(name='Students'))
        real_user = auth.authenticate(username=username, password=password)
        auth.login(request, real_user)
        return HttpResponseRedirect(reverse('grades:tutorial'))
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('grades:courses'))
        else:
            error_message = "You entered an incorrect username and/or password. Please try again. (Click this message to close it.)"
            context = {
            'error_message': error_message,
            }
            return render(request, 'gradebook/index.html', context)
    elif request.user.is_authenticated():
        return HttpResponseRedirect(reverse('grades:courses'))
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('grades:index'))


def courses(request):
    if request.user.is_authenticated():
        groups = request.user.groups.values_list('name', flat=True)
        if 'Students' in groups:
            name = request.user.first_name+' '+request.user.last_name
            try:
                student = Student.objects.get(name=name)
                courses = student.courses.all()
                courses_sorted = sorted(courses, key=attrgetter('code'))
                context = {
                'student': student,
                'courses': courses_sorted,
                }
                return render(request, 'gradebook/student_courses.html', context)
            except:
                error_message = "You haven't been added to Gradebook by any of your professors yet. (Click this message to close it.)"
                context = {
                'error_message': error_message,
                }
                return render(request, 'gradebook/index.html', context)
        else:
            courses = Course.objects.filter(user=request.user)
            courses_sorted = sorted(courses, key=attrgetter('code'))
            context = {
            'user': request.user,
            'courses': courses_sorted,
            }
            return render(request, 'gradebook/courses.html', context)
    else:
        HttpResponseRedirect(reverse('grades:index'))


def add_course(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            name = request.POST.get('course_name', '')
            code = request.POST.get('course_code', '')
            credits = int(request.POST.get('number_of_credits', '0'))
            grading = request.POST.get('grading', 'relative')
            if 'relative' in grading:
                relative_grading = True
            else:
                relative_grading = False
            course = Course(code=code, name=name, number_of_credits=credits, relative_grading=relative_grading, user=request.user, date_created=datetime.now())
            course.save()
            return HttpResponseRedirect(reverse('grades:add_students'))
        else:
            return render(request, 'gradebook/add_course.html', )
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def course_details(request, course_id):
    if request.user.is_authenticated():
        groups = request.user.groups.values_list('name', flat=True)
        if 'Students' in groups:
            name = request.user.first_name+' '+request.user.last_name
            student = Student.objects.get(name=name)
            course = Course.objects.get(id=course_id)
            assignments = course.assignments()
            marks = {}
            percentages = {}
            for assignment in assignments:
                marks[assignment] = float(Marks.objects.get(course=course, assignment=assignment, student=student).marks)
                percentages[assignment] = round(100.0*(marks[assignment]/float(assignment.total_marks)), 2)
            context = {
            'student': student,
            'course': course,
            'assignments': assignments,
            'marks': marks,
            'percentages': percentages,
            }
            return render(request, 'gradebook/student_course_details.html', context)
        else:
            course = Course.objects.get(id=course_id)
            students = course.students()
            assignments  = course.assignments()
            students_marks = course.students_marks()
            marks_count_unordered = dict(Counter(students_marks.values()))
            marks_count_ordered = OrderedDict(sorted(marks_count_unordered.items()))
            assignment_marks = []
            for assignment in assignments:
                assignment_marks.append(assignment.students_marks())
            context = {
            'course': course,
            'students': students,
            'assignments': assignments,
            'assignment_marks': assignment_marks,
            'students_marks': students_marks,
            'marks_count': marks_count_ordered,
            }
            return render(request, 'gradebook/course_details.html', context)
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def assign_grades(request, course_id):
    if request.user.is_authenticated():
        course = Course.objects.get(id=course_id)
        students = course.students()
        students_marks = course.students_marks()
        grades = course.assign_grades()
        grades_count_unordered = dict(Counter(grades.values()))
        grades_count_ordered = OrderedDict(sorted(grades_count_unordered.items()))
        context = {
        'course': course,
        'students': students,
        'students_marks': students_marks,
        'grades': grades,
        'grades_count': grades_count_ordered,
        }
        return render(request, 'gradebook/assign_grades.html', context)
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def edit_course(request, course_id):
    if request.user.is_authenticated():
        course = Course.objects.get(id=course_id)
        if request.method == 'POST':
            course.code = request.POST.get('course_code', '')
            course.name = request.POST.get('course_name', '')
            course.number_of_credits = int(request.POST.get('number_of_credits', '0'))
            grading = request.POST.get('grading', '')
            if 'relative' in grading:
                course.relative_grading = True
            else:
                course.relative_grading = False
            course.save()
            return HttpResponseRedirect(reverse('grades:course_details', args=(course.id,)))
        else:
            if course.relative_grading == True:
                relgrade = True
            else:
                relgrade = False
            context = {
            'course': course,
            'relgrade': relgrade,
            }
            return render(request, 'gradebook/edit_course.html', context)
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def delete_course(request, course_id):
    if request.user.is_authenticated():
        course = Course.objects.get(id=course_id)
        if request.method == 'POST':
            choice = request.POST.get('delete', '')
            if 'yes' in choice:
                course.delete()
                return HttpResponseRedirect(reverse('grades:courses'))
            else:
                return HttpResponseRedirect(reverse('grades:course_details', args=(course.id,)))
        else:
            return HttpResponseRedirect(reverse('grades:course_details', args=(course.id,)))
    else:
        return HttpResponseRedirect(reverse('grades:index'))


def students(request):
    if request.user.is_authenticated():
        courses = Course.objects.filter(user=request.user)
        students = []
        for course in courses:
            students += course.students()
        students = list(set(students))
        students_sorted = sorted(students, key=attrgetter('id'))
        average_marks = {}
        for student in students_sorted:
            average_marks[student] = student.average_marks()
        marks_count_unordered = dict(Counter(average_marks.values()))
        marks_count_ordered = OrderedDict(sorted(marks_count_unordered.items()))
        context = {
        'courses': courses,
        'students': students_sorted,

gradebook/templates/gradebook/add_assignment.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <title>Gradebook: Add Assignment</title>

        <meta charset="utf-8">
        <meta name="description" content="Managing your students' academic records just got a whole lot easier.">
        <meta name="keywords" content="">
        <meta name="author" content="Anirban Sengupta">

        <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/base.css' %}" />
        <link rel="shortcut icon" href="{% static 'gradebook/favicon.ico' %}" />

        <!--[if lte IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body>

            <table class="banner"><tbody><tr><td>

                <a href="{% url 'grades:courses' %}"><span id="logo">gradebook</span></a>

            </td><td id="navigation1">

                <a href="{% url 'grades:courses' %}"><span class="nav"> Courses </span></a>
                <a href="{% url 'grades:students' %}"><span class="nav"> Students </span></a>
                <a href="{% url 'grades:assignments' %}"><span id="current"> Assignments </span></a>
                <a href="{% url 'grades:profile' %}"><span class="nav"> Profile </span></a>
                <a href="{% url 'grades:tutorial' %}"><span class="nav"> Help </span></a>
                <a href="{% url 'grades:logout' %}"><span id="logout"> Log out </span></a>

            </td></tr></tbody></table>

        <table class="lower_banner"><tbody><tr>
                <td><span id="intro">Add assignment</span></td>
                <td id="navigation2">
                <a href="{% url 'grades:add_course' %}"><span class="display_other">Add course</span></a>
                <a href="{% url 'grades:add_students' %}"><span class="display_other">Add students</span></a>
                <a href="{% url 'grades:add_marks' %}"><span class="display_other">Add marks</span></a>
            </td></tr></tbody></table>

        {% if courses %}
        <div id="add_assignment">
            
            <form name="add_assignment" action="{% url 'grades:add_assignment' %}" method="post">
                {% csrf_token %}

                    Select course&nbsp;&nbsp;&nbsp;
                    <select id="course" name="course">
                        {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.code }}&nbsp;{{ course.name }}</option>
                        {% endfor %}
                    </select><br />
                Assignment name&nbsp;&nbsp;&nbsp;<input id="large1" type="text" name="assignment_name" autofocus="autofocus" /><br />
                Assignment description<br />
                <textarea rows="2" cols="60" id="students" name="assignment_description" /></textarea><br />
                Total marks&nbsp;&nbsp;&nbsp;<input class="small" type="text" name="total_marks" /><br />
                Weightage (in marks)&nbsp;&nbsp;&nbsp;<input class="small" type="text" name="weightage" /><br /><br />
                <input id="button" type="submit" value="Continue"/>

            </form>

        </div>

        {% else %}

            <div class="text">
                <p>Please add a course first.</p>
            </div>

        {% endif %}

    </body>

</html>

gradebook/templates/gradebook/add_marks.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <title>Gradebook: Add Marks</title>

        <meta charset="utf-8">
        <meta name="description" content="Managing your students' academic records just got a whole lot easier.">
        <meta name="keywords" content="">
        <meta name="author" content="Anirban Sengupta">

        <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/base.css' %}" />
        <link rel="shortcut icon" href="{% static 'gradebook/favicon.ico' %}" />

        <!--[if lte IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body>

            <table class="banner"><tbody><tr><td>

                <a href="{% url 'grades:courses' %}"><span id="logo">gradebook</span></a>

            </td><td id="navigation1">

                <a href="{% url 'grades:courses' %}"><span class="nav"> Courses </span></a>
                <a href="{% url 'grades:students' %}"><span class="nav"> Students </span></a>
                <a href="{% url 'grades:assignments' %}"><span id="current"> Assignments </span></a>
                <a href="{% url 'grades:profile' %}"><span class="nav"> Profile </span></a>
                <a href="{% url 'grades:tutorial' %}"><span class="nav"> Help </span></a>
                <a href="{% url 'grades:logout' %}"><span id="logout"> Log out </span></a>

            </td></tr></tbody></table>

            <table class="lower_banner"><tbody><tr>
                <td><span id="intro">Add marks</span></td>
                <td id="navigation2">
                <a href="{% url 'grades:add_course' %}"><span class="display_other">Add course</span></a>    
                <a href="{% url 'grades:add_students' %}"><span class="display_other">Add students</span></a>
                <a href="{% url 'grades:add_assignment' %}"><span class="display_other">Add assignment</span></a>
            </td></tr></tbody></table>

        {% if courses %}
        <div id="add_marks">
            
            <form name="add_marks" action="{% url 'grades:add_marks' %}" method="post">
                {% csrf_token %}

                    Select course<br />
                    <select id="course" name="course">
                        {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.code }}&nbsp;{{ course.name }}</option>
                        {% endfor %}
                    </select><br />

                    {% if course_selected %}
                        {% if course_selected.assignments %}
                        Select assignment<br />
                        <select id="assignment" name="assignment">
                            {% for assignment in course_selected.assignments %}
                            <option value="{{ assignment.id }}">{{ assignment.name }}</option>
                            {% endfor %}
                        </select><br />
                        Enter marks, separated by spaces/commas, as<br />
                        <input class="form" type="radio" name="marks_entry" value="only_marks" />Only marks, in order of student ID&nbsp;&nbsp;&nbsp;
                        <input class="form" type="radio" name="marks_entry" value="marks_and_id" />Marks and student ID on each line
                        <br />
                        <textarea id="marks" rows="10" cols="40" name="marks" /></textarea><br />
                        {% else %}
                        Please add an assignment for this course first.<br />
                        {% endif %}

                    {% elif assignments %}
                        Select assignment<br />
                        <select id="assignment" name="assignment">
                            {% for assignment in assignments %}
                            <option value="{{ assignment.id }}">{{ assignment.name }}</option>
                            {% endfor %}
                        </select><br />
                        Enter marks, separated by spaces/commas, as<br />
                        <input class="form" type="radio" name="marks_entry" value="only_marks" />Only marks, in order of student ID&nbsp;&nbsp;&nbsp;
                        <input class="form" type="radio" name="marks_entry" value="marks_and_id" />Marks and student ID on each line
                        <br />
                        <textarea id="marks" rows="10" cols="40" name="marks" /></textarea><br />

                    {% endif %}
                <input id="button" type="submit" value="Continue"/>

            </form>

        </div>

        {% else %}

            <div class="text">
                <p>Please add a course first.</p>
            </div>

        {% endif %}

    </body>

</html>

gradebook/templates/gradebook/assignments.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <title>Gradebook: Assignments</title>

        <meta charset="utf-8">
        <meta name="description" content="Managing your students' academic records just got a whole lot easier.">
        <meta name="keywords" content="">
        <meta name="author" content="Anirban Sengupta">

        <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/base.css' %}" />
        <link rel="shortcut icon" href="{% static 'gradebook/favicon.ico' %}" />

        <!--[if lte IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body>

            <table class="banner"><tbody><tr><td>

                <a href="{% url 'grades:courses' %}"><span id="logo">gradebook</span></a>

            </td><td id="navigation1">

                <a href="{% url 'grades:courses' %}"><span class="nav"> Courses </span></a>
                <a href="{% url 'grades:students' %}"><span class="nav"> Students </span></a>
                <span id="current"> Assignments </span>
                <a href="{% url 'grades:profile' %}"><span class="nav"> Profile </span></a>
                <a href="{% url 'grades:tutorial' %}"><span class="nav"> Help </span></a>
                <a href="{% url 'grades:logout' %}"><span id="logout"> Log out </span></a>

            </td></tr></tbody></table>

            <table class="lower_banner"><tbody><tr>
                <td><span id="intro">All assignments</span></td>
                <td id="navigation2">
                <a href="{% url 'grades:add_course' %}"><span class="display_other">Add course</span></a>
                <a href="{% url 'grades:add_students' %}"><span class="display_other">Add students</span></a>
                <a href="{% url 'grades:add_assignment' %}"><span class="display_other">Add assignment</span></a>
                <a href="{% url 'grades:add_marks' %}"><span class="display_other">Add marks</span></a>
            </td></tr></tbody></table>

        {% if assignments %}

        <div id="main_table">

            <table id="main"><tbody>

                <tr id="titles">
                    <td class="titles">Course code</td>
                    <td class="titles">Name</td>
                    <td class="titles">Description</td>
                    <td class="titles">Average marks</td>
                    <td class="titles">Maximum marks</td>
                </tr>

                {% for assignment in assignments %}
                    <tr class="table_link" onclick="document.location='{% url 'grades:assignment_details' assignment.id %}' ">
                        <td class="elements">{{ assignment.course.code }}</td>
                        <td class="elements">{{ assignment.name }}</td>
                        <td class="elements">{{ assignment.description }}</td>
                        <td class="elements">{{ assignment.average_marks }}</td>
                        <td class="elements">{{ assignment.total_marks }}</td>
                    </tr>
                {% endfor %}

            </tbody></table>

        </div>

        {% else %}

                {% if not courses %}
            <div class="text">
                <p>Please add a course first.</p>
            </div>
            
            {% else %}
            
            <div class="text">
                <p>It looks like you haven't added any students yet.</p>
            </div>

            {% endif %}

        {% endif %}

    </body>

</html>

gradebook/templates/gradebook/edit_course.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <title>Gradebook: Edit {{ course.code }}</title>

        <meta charset="utf-8">
        <meta name="description" content="Managing your students' academic records just got a whole lot easier.">
        <meta name="keywords" content="">
        <meta name="author" content="Anirban Sengupta">

        <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/base.css' %}" />
        <link rel="shortcut icon" href="{% static 'gradebook/favicon.ico' %}" />
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'gradebook/javascript/edit_course.js' %}"></script>

        <!--[if lte IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body>

            <table class="banner"><tbody><tr><td>

                <a href="{% url 'grades:courses' %}"><span id="logo">gradebook</span></a>

            </td><td id="navigation1">

                <a href="{% url 'grades:courses' %}"><span id="current"> Courses </span></a>
                <a href="{% url 'grades:students' %}"><span class="nav"> Students </span></a>
                <a href="{% url 'grades:assignments' %}"><span class="nav"> Assignments </span></a>
                <a href="{% url 'grades:profile' %}"><span class="nav"> Profile </span></a>
                <a href="{% url 'grades:tutorial' %}"><span class="nav"> Help </span></a>
                <a href="{% url 'grades:logout' %}"><span id="logout"> Log out </span></a>

            </td></tr></tbody></table>

            <table class="lower_banner"><tbody><tr>
                <td><span id="intro">Edit {{ course.code }}: {{ course.name }}</span></td>
                <td id="navigation2">
                <span id="display_chart">Delete course</span>
                <span id="display_table">Edit course</span>
                <a href="{% url 'grades:add_course' %}"><span class="display_other">Add course</span></a>
                <a href="{% url 'grades:add_students' %}"><span class="display_other">Add students</span></a>
                <a href="{% url 'grades:add_assignment' %}"><span class="display_other">Add assignment</span></a>
            </td></tr></tbody></table>

        <div id="add_course">
            
            <form name="add_course" action="{% url 'grades:edit_course' course.id %}" method="post">
                {% csrf_token %}

                Course code&nbsp;&nbsp;&nbsp;<input class="small" type="text" name="course_code" autofocus="autofocus" value="{{ course.code }}" /><br />
                Course name&nbsp;&nbsp;&nbsp;<input class="large" type="text" name="course_name" value="{{ course.name }}" /><br />
                Number of credits&nbsp;&nbsp;&nbsp;<input class="small" type="text" name="number_of_credits" value="{{ course.number_of_credits }}" /><br />
                <div id="grading_system">Grading system&nbsp;&nbsp;&nbsp;<input class="form" type="radio" name="grading" value="relative" {% if relgrade %}checked{% endif %} />Relative&nbsp;&nbsp;&nbsp;<input class="form" type="radio" name="grading" value="absolute" {% if not relgrade %}checked{% endif %} />Absolute</div><br />
                <input id="button" type="submit" value="Continue"/>

            </form>

        </div>

        <div id="delete">
            <form name="delete" action="{% url 'grades:delete_course' course.id %}" method="post">
                {% csrf_token %}
            <p>Are you sure you want to delete this course?</p>
            <p><input class="form" type="radio" name="delete" value="yes" />Yes&nbsp;&nbsp;&nbsp;<input class="form" type="radio" name="delete" value="no" />No</p>
            <input id="button" type="submit" value="Continue"/>
            </form>
        </div>

    </body>

</html>

gradebook/templates/gradebook/edit_student.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <title>Gradebook: Edit {{ student.id }}</title>

        <meta charset="utf-8">
        <meta name="description" content="Managing your students' academic records just got a whole lot easier.">
        <meta name="keywords" content="">
        <meta name="author" content="Anirban Sengupta">

        <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/base.css' %}" />
        <link rel="shortcut icon" href="{% static 'gradebook/favicon.ico' %}" />

        <!--[if lte IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body>

            <table class="banner"><tbody><tr><td>

                <a href="{% url 'grades:courses' %}"><span id="logo">gradebook</span></a>

            </td><td id="navigation1">

                <a href="{% url 'grades:courses' %}"><span id="current"> Courses </span></a>
                <a href="{% url 'grades:students' %}"><span class="nav"> Students </span></a>
                <a href="{% url 'grades:assignments' %}"><span class="nav"> Assignments </span></a>
                <a href="{% url 'grades:profile' %}"><span class="nav"> Profile </span></a>
                <a href="{% url 'grades:tutorial' %}"><span class="nav"> Help </span></a>
                <a href="{% url 'grades:logout' %}"><span id="logout"> Log out </span></a>

            </td></tr></tbody></table>

            <table class="lower_banner"><tbody><tr>
                <td><span id="intro">Edit {{ student.id }}: {{ student.name }}</span></td>
                <td id="navigation2">
                <a href="{% url 'grades:add_course' %}"><span class="display_other">Add course</span></a>
                <a href="{% url 'grades:add_students' %}"><span class="display_other">Add students</span></a>
                <a href="{% url 'grades:add_assignment' %}"><span class="display_other">Add assignment</span></a>
            </td></tr></tbody></table>

        <div id="add_course">
            
            <form name="add_course" action="{% url 'grades:edit_student' student.id %}" method="post">
                {% csrf_token %}

                Student ID&nbsp;&nbsp;&nbsp;<input class="small" type="text" name="student_code" autofocus="autofocus" value="{{ student.id }}" /><br />
                Student name&nbsp;&nbsp;&nbsp;<input class="large" type="text" name="student_name" value="{{ student.name }}" /><br /><br />
                <input id="button" type="submit" value="Continue"/>

            </form>

        </div>

    </body>

</html>